### ISSUE TITLE
9.0 出现如下问题

### ISSUE THREAD

**Issue by RookieApe** [shmy/flutter_video_player#2]
E/ExoPlayerImplInternal(22444): Caused by: java.io.IOException: Cleartext HTTP traffic to ferbyufgeruy.pprchina.com not permitted

**Comment by shmy** [comment]
你好 我这边安卓9正常 你是华为手机吗


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by RookieApe** [comment]
是的，华为荣耀 magic2
对了，应该是播放链接是 http 不是 https 的问题
